<?php
/**
 * @file
 * aleph.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function aleph_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_aleph_interest_period'
  $field_bases['field_aleph_interest_period'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_aleph_interest_period',
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        30 => '1 month',
        60 => '2 months',
        90 => '3 months',
        180 => '6 months',
        360 => '12 months',
      ),
      'allowed_values_function' => '',
      'profile2_private' => 0,
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_aleph_preferred_branch'
  $field_bases['field_aleph_preferred_branch'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_aleph_preferred_branch',
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(),
      'allowed_values_function' => 'aleph_get_branches',
      'profile2_private' => 0,
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
