<?php

/**
 * @file
 * Code for the Aleph feature.
 */

use Drupal\aleph\Aleph\AlephClient;
use Drupal\aleph\Aleph\Handler\AlephPatronHandler;

include_once 'aleph.features.inc';
require __DIR__ . '/vendor/autoload.php';

// Define date formats used by Aleph.
define('ALEPH_DATE_FORMAT', 'Ymd');

/**
 * Return array with branch keys and names.
 *
 * @return array
 *    Branch key => Branch name
 */
function aleph_get_branches() {
  return array(
    'BBAAA' => 'Borgarbókasafnið Grófinni',
    'BBFAA' => 'Borgarbókasafnið Spönginni',
    'BBKAA' => 'Borgarbókasafnið Kringlunni',
    'BBSAA' => 'Borgarbókasafnið Sólheimum',
    'BBGAA' => 'Borgarbókasafnið Gerðubergi',
    'BBRAA' => 'Borgarbókasafnið Árbæ',
    'BBNAA' => 'Borgarbókasafnið Norðlingaholti',
  );
}

/**
 * Returns list of allowed interest periods.
 *
 * @return array
 *   Array of days => human readable string.
 */
function aleph_get_interest_periods() {
  $periods = array(
    1 => 30,
    2 => 60,
    3 => 90,
    6 => 180,
    12 => 360,
  );
  $options = array();
  foreach ($periods as $months => $days) {
    $options[$days] = format_plural($months, '1 month', '@count months');
  }
  return $options;
}

/**
 * Implements hook_ding_provider().
 */
function aleph_ding_provider() {
  return array(
    'title' => 'Aleph provider',
    'settings' => 'aleph_settings_form',
    'provides' => array(
      'availability' => array(
        'prefix' => 'availability',
        'file' => 'includes/aleph.availability.inc',
      ),
      'user_consent' => array(
        'prefix' => 'user_consent',
        'file' => 'includes/aleph.user_consent.inc',
      ),
      'user' => array(
        'prefix' => 'user',
        'file' => 'includes/aleph.user.inc',
      ),
      'loan' => array(
        'prefix' => 'loan',
        'file' => 'includes/aleph.loan.inc',
      ),
      'reservation' => array(
        'prefix' => 'reservation',
        'file' => 'includes/aleph.reservation.inc',
      ),
      'debt' => array(
        'prefix' => 'debt',
        'file' => 'includes/aleph.debt.inc',
      ),
    ),
  );
}

/**
 * Form callback for provider module settings.
 *
 * This is a regular form callback.
 */
function aleph_settings_form() {
  $form = array();

  $form['aleph'] = array(
    '#type' => 'fieldset',
    '#title' => t('Aleph service settings'),
    '#tree' => FALSE,
  );

  $form['aleph']['aleph_base_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Aleph base URL'),
    '#description' => t('Base URL for Aleph service.'),
    '#required' => TRUE,
    '#default_value' => variable_get('aleph_base_url', ''),
  );

  $form['aleph']['aleph_base_url_rest'] = array(
    '#type' => 'textfield',
    '#title' => t('Aleph REST base URL'),
    '#description' => t('Base URL for Aleph REST service.'),
    '#required' => TRUE,
    '#default_value' => variable_get('aleph_base_url_rest', ''),
  );

  $form['aleph']['aleph_main_library'] = array(
    '#type' => 'textfield',
    '#title' => t('Aleph Main Library'),
    '#description' => t('The main library. ICE01 for example.'),
    '#required' => TRUE,
    '#default_value' => variable_get('aleph_main_library', ''),
  );

  $form['aleph']['aleph_enable_reservation_deletion'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable reservation deletion'),
    '#default_value' => variable_get('aleph_enable_reservation_deletion',
      FALSE),
    '#description' => t('Allow users to delete their reservations.'),
  );

  $form['aleph']['aleph_enable_logging'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable logging'),
    '#default_value' => variable_get('aleph_enable_logging', FALSE),
    '#description' => t('Logs requests to the Aleph webservice. Sensitive information such as CPR number and PIN code is stripped from the requests.'),
  );

  // Add the option to select a default interest period for reservations, if not
  // selected it will default to 360 days (12 months). The users can override
  // this during reservation.
  $allowed_values = array(
    30 => '1 month',
    60 => '2 months',
    90 => '3 months',
    180 => '6 months',
    360 => '12 months',
  );
  $default = variable_get('aleph_default_interest_period', 360);
  $form['aleph'] += ding_reservation_interest_period_selector('aleph_default_interest_period', $default, $allowed_values);

  return system_settings_form($form);
}

/**
 * Return a fully instantiated AlephClient instance.
 *
 * @return \Drupal\aleph\Aleph\AlephClient|null
 *    The Aleph client.
 */
function aleph_client() {
  // This is basically a singleton. We also wait until right before
  // instantiating to include our required classes. That seems like a
  // decent performance trade-off instead of loading everything on every
  // page load.
  static $client;
  if (!isset($client)) {
    try {
      $client = new AlephClient(
        variable_get('aleph_base_url', ''),
        variable_get('aleph_base_url_rest', ''),
        variable_get('aleph_main_library', ''),
        variable_get('aleph_filter_institution', '')
      );
    }
    catch (Exception $e) {
      watchdog('aleph', 'Constructor error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
      return NULL;
    }
  }
  return $client;
}

/**
 * Return an instance of the AlephPatron by account.
 *
 * @return \Drupal\aleph\Aleph\Entity\AlephPatron
 *    The Aleph Patron object.
 *
 * @throws \DingProviderAuthException
 *   Given operation cannot be completed until the user authenticates.
 */
function aleph_get_patron_by_account() {
  $patron_handler = new AlephPatronHandler(aleph_client());
  $credentials = ding_user_get_creds();
  return $patron_handler->authenticate($credentials['name'], $credentials['pass'])->getPatron();
}

/**
 * Add pincode validation to the patron's profile.
 */
function aleph_form_profile2_form_alter(&$form, &$form_state) {
  $form['#validate'][] = 'aleph_pin_form_validate';
}

/**
 * Pincode validation.
 */
function aleph_pin_form_validate($form, &$form_state) {
  $pincode = $form_state['values']['pincode'];

  if (!empty($pincode) && !ctype_alnum($pincode)) {
    form_set_error(
      'pass', t('Pincode must not contain special characters.')
    );
  }
}
