@startuml
!pragma revision 1
abstract class DingEntityBase
abstract class DingEntityCollection extends DingEntityBase
abstract class DingEntity extends DingEntityBase
class TingRelation extends DingEntityBase
class TingPseudoObject implements TingObjectInterface
class OpenSearchTingObject implements TingObjectInterface

TingCollection - "0..*" TingObjectCollectionInterface
class TingCollection extends DingEntityCollection {
  TingObjectCollectionInterface[] objects
  getObjects()
}

class TingEntity extends DingEntity {
  TingObjectInterface $reply
}


interface TingObjectCollectionInterface {
    getObjects()
    getPrimaryObject()
}




TingClientSearchResult - "0..*" TingCollection
class TingClientSearchResult {
  TingCollection[]
}


class OpenSearchTingObjectCollection implements TingObjectCollectionInterface {

}

class OpenSearchTingSearchResult implements TingSearchResultInterface {
  TingClientSearchResult $openSearchResult
}

TingSearchResultInterface - "0..*" TingCollection

interface TingSearchResultInterface {
    getNumTotalObjects()
    getNumTotalCollections()
    getCollections()
}
@enduml
